// Bundles the embeddable widget scripts that share code with the app.
//
// Widgets that need the typed targeting matcher live as ESM sources under
// widgets/ and `import` it straight from lib/attributes.ts — the single source
// of truth. esbuild inlines (tree-shakes) that pure module into a classic
// <script>-loadable IIFE under public/. The committed public/*.js are build
// OUTPUTS: edit the widgets/ source, then `npm run build:widgets`.
//
// Widgets with no shared code (public/widget.js, roadmap-widget.js,
// feedback-widget.js) stay hand-authored directly in public/ and are not built.

import { build } from "esbuild";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

const ENTRIES = ["announcement-widget.js", "changelog-widget.js"];

await build({
  entryPoints: ENTRIES.map((f) => join(root, "widgets", f)),
  outdir: join(root, "public"),
  bundle: true,
  format: "iife",
  platform: "browser",
  target: "es2017",
  // Readable output: these are committed and reviewed in diffs.
  minify: false,
  banner: {
    js: "/* GENERATED by scripts/build-widgets.mjs from widgets/ — do not edit here. */",
  },
  logLevel: "info",
});

console.log(`Built ${ENTRIES.length} widget(s) → public/`);
